from django.db import models

# id is generated by default in all models
# all fields are class attributes


# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15)
    ssn = models.CharField(max_length=15)
    address = models.TextField()
    age = models.IntegerField()
    gender = models.CharField(max_length=7)
    user_type = models.CharField(max_length=20)
    user_name = models.CharField(max_length=20)

class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    no_doses_received = models.IntegerField(default=0)
    race = models.CharField(max_length=50)
    occupation = models.CharField(max_length=50)
    medical_history = models.TextField()

class Nurse(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    emp_id = models.CharField(max_length=50)

class Vaccine(models.Model):
    name = models.CharField(max_length=255)
    number_doses_free = models.IntegerField(null=False, blank=False, default=0) #Use it to store what vaccine dose it is.
    on_hold = models.IntegerField(null=False, blank=False, default = 0)
    description = models.TextField(blank=True, null=True)
    total_availability = models.IntegerField(null=False, blank=False, default=100)

class Timeslot(models.Model):
    timestamp = models.DateTimeField(unique=True)      # do we need slots for that hour.. how to get hour?
    open_slots = models.IntegerField(default=0)      # number of slots that hour

class Appointment(models.Model):
    vaccine_dose = models.IntegerField()
    vaccine = models.ForeignKey(Vaccine, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    timeslot = models.ForeignKey(Timeslot, on_delete=models.CASCADE)

class Record(models.Model):
    apt_id = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    nurse = models.ForeignKey(Nurse, on_delete=models.CASCADE)

class Assigned(models.Model):
    nurse = models.ForeignKey(Nurse, on_delete=models.CASCADE)
    timeslot = models.ForeignKey(Timeslot, on_delete=models.CASCADE)
